### ISSUE TITLE
Missing type `null` for BreadcrumbRoute

### ISSUE THREAD

**Issue by jannisg** [icd2k3/use-react-router-breadcrumbs#12]
In your API docs you mention:
```
breadcrumb?: String|Component|null
```

However the actual types for this are:
```ts
export interface BreadcrumbsRoute {
  path: string;
  breadcrumb?: React.ComponentType | React.ElementType | string;        // <== missing the `null` type
  matchOptions?: MatchOptions;
  routes?: BreadcrumbsRoute[];
}
```

If I understand the use case for skipping a breadcrumb for a certain route correctly, then I think the `null` type should be allowed for `breadcrumb` as otherwise any declaration of:
```ts

const crumbs = useBreadcrumbs([
  { path: "/", breadcrumb: null },
]);
```

would be invalid/throwing typescript errors.

Am I correct in assuming `null` _should_ in fact be allowed here?

**Comment by icd2k3** [comment]
I'll update this soon, sorry for the delay!
