### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ferdingler** [icd2k3/use-react-router-breadcrumbs#13]
Good job developing this library! I love how simple and [minimal](https://bundlephobia.com/result?p=use-react-router-breadcrumbs@1.0.4) it is. 

I notice from the package.json and the header in the source files that this is released under the MIT license, but seems like the LICENSE file is missing from the root of the repository. I suggest adding it.

**Comment by icd2k3** [comment]
Thanks for the heads up! I'll add one soon
