### ISSUE TITLE
Recursive routes

### ISSUE THREAD

**Issue by edewit** [icd2k3/use-react-router-breadcrumbs#18]
More of a question that a real issue. I have a application where we have a recursive route. Groups have groups and by clicking on one of the groups of a group you navigate down one group. Url looks like this `http://locahost:8080/groups/1/2/0` where the numbers are the ids of the groups now this works with use-react-router-breadcrumbs as I create a route with `exact` off I get a breadcrumb like: `groups > 1 > 2 > 0` now I would like the names of the groups instead of the ids. Is there a way to accomplish this? I can't use the route state because it's just one route.

**Comment by edewit** [comment]
My current solution is a bit hacky, I count the number of times my breadcrumb name component is being rendered and render the name for that part of the url:
```typescript
let index = -1;
export const GroupName = ({ location }: { location: { pathname: string } }) => {
  const [group, setGroup] = useState<GroupRepresentation>();

  useEffect(() => {
    let mounted = true;
    const ids = getId(location.pathname);
    index++;
    adminClient.groups.findOne({ id: ids[index] }).then((group) => {
      if (mounted) {
        setGroup(group);
      }
    });
    return () => {
      index--;
      mounted = false;
    };
  }, []);
  return (
    <>
      {group && (
        <span key={group.id}>{group.name}</span>
      )}
    </>
  );
};

```

**Comment by icd2k3** [comment]
Hi @edewit If I'm understanding the use-case correctly, I'd probably try something like this:

[I set up a codesandbox with my first thought to approach this problem](https://codesandbox.io/s/use-react-router-breadcrumbs-groups-example-k2y8k?file=/routeConfig.js)

```js
const mockGroupNames = {
  1: "Group One",
  2: "Group Two",
  3: "Group Three"
};

const routeConfig = [{
  path: "/groups/:groupId/:groupIdNext?/:groupIdLast?",
  breadcrumb: ({
    match: {
      params: { groupId, groupIdNext, groupIdLast }
    }
  }) => <span>{mockGroupNames[groupIdLast || groupIdNext || groupId]}</span>
}];

useBreadcrumbs(routeConfig)
```

**Comment by edewit** [comment]
Right this works for a fixed number of groups, but mine are dynamic and there could always be another level that is why I use the pathname and to figure out the number of ids myself, but that introduces the problem that in the "Breadcrumb name" component I doesn't know which one I should render.

[I created a fork of you example](https://codesandbox.io/s/use-react-router-breadcrumbs-groups-example-forked-3zw9l?file=/routeConfig.js)

**Comment by icd2k3** [comment]
oh ok, thanks for clarifying for me! In this case, I think your approach is probably the best bet - there isn't anything in this package currently to handle dynamic recursive paths

**Comment by edewit** [comment]
Right okay thanks
