### ISSUE TITLE
Typedefs missing in v2.0.1  (were ok in 2.0.0)

### ISSUE THREAD

**Issue by jafin** [icd2k3/use-react-router-breadcrumbs#28]
## Bug?

Typescript typedefs missing from 2.0.1 NPM package.
Working fine in v2.0.0

Checked node_modules/._..breadcrumbs..._/dist
Could not locate index.d.ts

Reinstalled 2.0.0, types returned.

**Comment by icd2k3** [comment]
oops - yep you're correct. I updated dev dependencies with 2.0.1 and it seems along the way the build has stopped generating the typedefs.

rest assured 2.0.1 is not functionally different than 2.0.0 - so please use that in the short team. I'll fix typedefs in 2.0.2
