### ISSUE TITLE
Not able to use as Could not find a declaration file for module 'use-react-router-breadcrumbs'. 

### ISSUE THREAD

**Issue by jocgaurav** [icd2k3/use-react-router-breadcrumbs#3]
Could not find a declaration file for module 'use-react-router-breadcrumbs'. 'c:/git/node_modules/use-react-router-breadcrumbs/dist/cjs/index.js' implicitly has an 'any' type.

**Comment by icd2k3** [comment]
Thanks @jocgaurav this will be fixed when the PR above is merged/deployed to v `1.0.2`
