### ISSUE TITLE
Config format does not match that of React Router Config

### ISSUE THREAD

**Issue by jonkoops** [icd2k3/use-react-router-breadcrumbs#30]
Compatibility with React Router is mentioned in the [README](https://github.com/icd2k3/use-react-router-breadcrumbs#route-config-compatibility), however the config format of the library actually does not match that of React Router.

Specifically the `matchOptions` which are a separate object in this library, whilst they are present on the main route configuration in React Router. For more information see the [type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router-config/index.d.ts#L24-L25) for React Router Config.

**Comment by icd2k3** [comment]
Thanks for reporting @jonkoops - I agree we should _match_ 😏  the `matchOptions` types in this package too

**Comment by icd2k3** [comment]
React router 6 has been released and this repo has been updated - if types are incorrect for something moving forward I'll re-open!
