### ISSUE TITLE
Support React Router v6

### ISSUE THREAD

**Issue by Grapedge** [icd2k3/use-react-router-breadcrumbs#31]
Now, React Router v6 has been released: [React Router](https://reactrouter.com/docs/en/v6).

Benefit from nested routing, there may be an easier way to achieve breadcrumbs: [API: matchRoutes](https://reactrouter.com/docs/en/v6/api#matchroutes)

Thank you for your works, If possible, I’d like to submit a PR.

**Comment by icd2k3** [comment]
Thanks @Grapedge! I hope to support v6 soon, but it might be a week or so before I can get around to it. In the meantime, PRs are certainly welcome if you'd like it sooner.

**Comment by Grapedge** [comment]
I will do related work this weekend, but there may be some changes, I will try to make it easy to migrate and close to the style of ReactRouter v6, I will organize it into a list first. Tomorrow I will create a PR and discuss which changes can be accepted.

**Comment by icd2k3** [comment]
Merged and released `v3.0.0` - thanks again @Grapedge !
