### ISSUE TITLE
Custom breadcrumb name when fetching data

### ISSUE THREAD

**Issue by rtransat** [icd2k3/use-react-router-breadcrumbs#37]
Hi!

I have read the docs and I would like to pass a custom component to a dynamic [route](https://codesandbox.io/s/priceless-ardinghelli-vi6og?file=/src/routes.js:265-299) but how to pass the data to the props ? I don't use redux or ReactContext.

You can check the exemple [here](https://codesandbox.io/s/priceless-ardinghelli-vi6og?file=/src/pages/Project.jsx)

I fetch data in `Project` component and I would like to have the data inside the `Breadcrumd` component to display the title.

Can you provide some example?

Regards.

**Comment by icd2k3** [comment]
Hi @rtransat - redux, context, or some other state sharing technique would probably work best for that...

However, breadcrumb can also be a function, so you could dynamically define your routes config after data is fetched and do something like `breadcrumb: () => <SomeBreadcrumbComponent data={data} />`

**Comment by icd2k3** [comment]
Closing for now
