### ISSUE TITLE
Please added feature disabledLink to allow to disable link if not needed

### ISSUE THREAD

**Issue by phatify** [icd2k3/use-react-router-breadcrumbs#41]
Please update this feature, this will be useful in some cases
, I mentioned an example for usage below: 

```
const configs = [
  { path: '/', breadcrumb: 'Home' },
  { path: '/product', breadcrumb: 'Product', disabledLink: true },
  { path: '/product/add', breadcrumb: 'New Product' },
]
```

```
  const breadcrumbs = useBreadcrumbs(configs, { 
    disableDefaults: true 
  });

  return (
    <>
      { breadcrumbs.map((data, i) => {
        const { match, breadcrumb } = data;
        return (
          <BreadcrumbComponent key={match.pathname}>
            {match.disabledLink ?
              <>{breadcrumb}</>
               :
              <Link to={match.pathname}>{breadcrumb}</Link>          
            } 
          </BreadcrumbComponent>                   
        )
      })}
    </>
  )
```

**Comment by icd2k3** [comment]
@phatify - all additional pass-through props (props that aren't part of the `react-router` or `use-react-router-breadcrumbs` APIs) are included at the root level of the map.

So your code should look something like this instead:

```js
return (
    <>
      { breadcrumbs.map((data, i) => {
        const { match, breadcrumb, disabledLink } = data;
        return (
          <BreadcrumbComponent key={match.pathname}>
            {disabledLink ?
              <>{breadcrumb}</>
               :
              <Link to={match.pathname}>{breadcrumb}</Link>          
            } 
          </BreadcrumbComponent>                   
        )
      })}
    </>
  )
```

**Comment by phatify** [comment]
> @phatify - all additional pass-through props (props that aren't part of the `react-router` or `use-react-router-breadcrumbs` APIs) are included at the root level of the map.
> 
> So your code should look something like this instead:
> 
> ```js
> return (
>     <>
>       { breadcrumbs.map((data, i) => {
>         const { match, breadcrumb, disabledLink } = data;
>         return (
>           <BreadcrumbComponent key={match.pathname}>
>             {disabledLink ?
>               <>{breadcrumb}</>
>                :
>               <Link to={match.pathname}>{breadcrumb}</Link>          
>             } 
>           </BreadcrumbComponent>                   
>         )
>       })}
>     </>
>   )
> ```

@icd2k3 Have you tried yet? It not works, bro! I got the `undefined ` from `console.log(disabledLink)`

**Comment by icd2k3** [comment]
@phatify I forgot to post the route config as well - pass through props have to be placed in a `props` object:

```js
const breadcrumbs = useBreadcrumbs([
    { path: "/", breadcrumb: "Home" },
    { path: "/product", breadcrumb: "Product", props: { disabledLink: true } },
    { path: "/product/add", breadcrumb: "New Product" }
  ]);
```

Here's a codesandbox example of the functionality you're looking for I think https://codesandbox.io/s/use-react-router-breadcrumbs-demo-forked-vxhvn?file=/Breadcrumbs.js

**Comment by icd2k3** [comment]
This props option is also noted in the [api section of the readme](https://github.com/icd2k3/use-react-router-breadcrumbs#api) but might be worth having it's own section if we see more questions like this

**Comment by phatify** [comment]
@icd2k3  Thanks for your answer. Its saved my time. :)))

**Comment by icd2k3** [comment]
No problem @phatify and sorry for the confusion - I've adjusted the "advanced" example in the readme slightly to highlight the `props` object. Closing this issue because it sounds like it solved your issue.
