### ISSUE TITLE
Humanize function should replace hyphens with spaces

### ISSUE THREAD

**Issue by codytooker** [icd2k3/use-react-router-breadcrumbs#42]
First off I would like to say this library is great and helps tremendously with breadcrumbs.

I would like to suggest though that `hyphens` should be treated just like `underscores` in the default setting. Hyphens in url's are way more often two words put together and not an actual hyphenated word.

I would like to suggest making this update to the Humanize function in the library.  I know this would probably require a major version bump since it would potentially break some peoples use cases. So an alternative could be to instead an option to `useBreadCrumbs` that allows the user to implement their own default handling.

**Comment by icd2k3** [comment]
Thanks @codytooker - I agree with you the automatic humanize method could be better 🤔  - in the meantime I like your suggestion & PR of having the option to provide your own humanize function

**Comment by icd2k3** [comment]
Implemented in `3.1.0` - thanks @codytooker !
