### ISSUE TITLE
Get "title" of current route

### ISSUE THREAD

**Issue by TutoDS** [icd2k3/use-react-router-breadcrumbs#45]
Hi
is possible get the "title" (the result of breadcrumb inside map) for the current route?

**Comment by icd2k3** [comment]
Hi @TutoDS 👋 - I'm not sure I understand what you're trying to do. Could you please elaborate a little more, or maybe a code example?

**Comment by TutoDS** [comment]
I have `/admin` route, but I want change `Admin` to `Dashboard` on breadcrumbs.
Any way to do that?

**Comment by steodor** [comment]
Hi @TutoDS, sure, but you need to dive into the Advanced section of the docs. From what I understand so far there are at least 2 ways to do this:

1. If you only display breadcrumbs on a small number of pages, then maybe this will suffice:
```js
// define custom breadcrumbs for certain routes.
// breadcumbs can be components or strings.
const routes = [
  { path: '/admin', breadcrumb: 'Dashboard' },
];

// map & render your breadcrumb components however you want.
const Breadcrumbs = () => {
  const breadcrumbs = useBreadcrumbs(routes);
  // [...]
}
```

2. If you are using `react-router@^6.x.x` and a `RouteObject`, you can specify the breadcrumbs directly in the `RouteObject` and pass that into the breadcrumbs hook, like so:
```js
const routeObject = [
  { path: '/admin', element: <AdminPage />, breadcrumb: 'Dashboard' },
  // ...rest of your routes
];

const Routes = () => {
  const element = useRoutes(routeObject);

  //... return your layout which renders {element} at some point
};

const Breadcrumbs = () => {
  const breadcrumbs = useBreadcrumbs(routeObject);
  // [...]
}
```
Note how `routeObject` is passed to both hooks, saving some boilerplate code. I went with this option and it works perfectly.

@icd2k3 I only stumbled upon this package a few hours ago, so have i missed anything?
Great job on this library, works like a charm! Thank you for your time! 👍

**Comment by icd2k3** [comment]
Thanks for responding @steodor! That's exactly right.

@TutoDS by default this package will create breadcrumbs for you based on the route path section (admin -> "Admin"), but you can manually set any of these by providing a route config array to the hook (like in @steodor's example).

**Comment by TutoDS** [comment]
OK, so this way, I create a json object and use to the routes and the breadcrumbs?
![image](https://user-images.githubusercontent.com/18479474/155194709-da69b289-b2c8-463c-b058-56917747315e.png)
How you transform this routes into the object?

**Comment by TutoDS** [comment]
And for example the route `:category/:slug`, I don't have the `:category` route, is possible remove the link for that "link"?

**Comment by icd2k3** [comment]
> OK, so this way, I create a json object and use to the routes and the breadcrumbs?

Yep, `use-react-router-breadcrumbs` accepts an array of route objects to override the default generated ones. There's an example of a config array in [the advanced section](https://github.com/icd2k3/use-react-router-breadcrumbs#advanced) of the docs.

> And for example the route :category/:slug, I don't have the :category route, is possible remove the link for that "route"?

If I understand correctly, you only want to display the `slug` part, correct? For example, a path of `/some-category/some-slug` would only result in a single breadcrumb of "Some Slug"?

If that's the case you'd probably want to disable the breadcrumb for :category. There are [a few ways](https://github.com/icd2k3/use-react-router-breadcrumbs#options) of doing this, but the easiest would be to just include a route config object of `{ path: ':category', breadcrumb: null }`.

**Comment by icd2k3** [comment]
Closing because over a month old, but will re-open if needed!
