### ISSUE TITLE
Compatibility with declarative Routes

### ISSUE THREAD

**Issue by YousefED** [icd2k3/use-react-router-breadcrumbs#46]
Is it possible to use https://github.com/icd2k3/use-react-router-breadcrumbs#advanced (the "breadcrumb" property") when using react-router and declarative, `<Route>` style routes?

Thanks!

**Comment by icd2k3** [comment]
You can not pass a `breadcrumb` prop into a `Route` component, but you can still define all the paths you're using and pass it into the breadcrumbs hook

```js
<Route path="example" element={<Example />} />

// ...

useBreadcrumbs({ path: '/example', breadcrumb: 'Custom' });
```

This will work, but I'd recommend using [route objects](https://reactrouter.com/docs/en/v6/examples/route-objects) because you can add a custom `breadcumb` property and pass the _same_ config into `react-router` and `use-react-router-breadcumbs` to keep everything in sync.

**Comment by MichaelDimmitt** [comment]
got a pr for this coming in 👍

**Comment by MichaelDimmitt** [comment]
you can track the change here
#49 @YousefED

**Comment by Kallb123** [comment]
I have pulled in `3.2.0` but I don't seem to be able to add breadcrumbs to my Route elements. I get the error:
```
Property 'breadcrumb' does not exist on type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | IndexRouteProps)'.
```

Possibly because I'm using TypeScript as well?

**Comment by MichaelDimmitt** [comment]
looks like you figured it out,

but one solution is to create a file that adds the type to Route from react-router
```
import React from 'react';
import { Route, PathRouteProps, LayoutRouteProps, IndexRouteProps } from 'react-router-dom';
type BreadCrumb = { breadcrumb: any }
type BreadCrumbRouteType = (_props: PathRouteProps | LayoutRouteProps | IndexRouteProps | BreadCrumb) => React.ReactElement<any, string | React.JSXElementConstructor<any>> | null
const BreadCrumbRoute: BreadCrumbRouteType = Route;

export { BreadCrumbRoute as Route }
```

then you import that Route instead.
`import { Route } from '<your_project>/<filename>'`

I can make a pr for this so that use-react-router-breadcrumbs will export Route instead of react-router

`import { Route, BreadcrumbsRoute } from 'use-react-router-breadcrumbs';`

**Comment by MichaelDimmitt** [comment]
The other solution is as you mentioned @Kallb123 

and the change would be for me just to update the docs

```
const GenerateAppRoutes = () => {
  // Full declarative react router support. example: Element, children, Nested Routes
  return (
    <Route path='/users/:userId' breadcrumb={DynamicUserBreadcrumb} element={<ProfilePage/>} />
    <Route path='/example' breadcrumb='Custom Example' >
      <Route path='/' breadcrumb='Custom Example' >
        <ExamplePage/>
      </Route>
    </Route>
    <Route path='/custom-props' breadcrumb={CustomPropsBreadcrumb} props={ someProp: 'Hi' } >
      <CustomPage/>
    </Route>
  )
};
```

changes to
const GenerateAppRoutes = () => {
  // Full declarative react router support. example: Element, children, Nested Routes
  return (
    < BreadCrumbRoute path='/users/:userId' breadcrumb={DynamicUserBreadcrumb} element={<ProfilePage/>} />
    < BreadCrumbRoute path='/example' breadcrumb='Custom Example' >
      < BreadCrumbRoute path='/' breadcrumb='Custom Example' >
        <ExamplePage/>
      </BreadCrumbRoute >
    </BreadCrumbRoute >
    < BreadCrumbRoute path='/custom-props' breadcrumb={CustomPropsBreadcrumb} props={ someProp: 'Hi' } >
      <CustomPage/>
    </BreadCrumbRoute >
  )
};

**Comment by MichaelDimmitt** [comment]
made a pr containing the first solution
#51

**Comment by icd2k3** [comment]
@MichaelDimmitt @Kallb123 - see if `3.2.1` checks all the boxes for ya!

**Comment by aaroni34** [comment]
Hi, this solution worked for me for generating the routes with breadcrumbs, but I'm not able to pass custom props.

Type '{ path: string; breadcrumb: any; element: Element; props: any; }' is not assignable to type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | (IndexRouteProps & BreadCrumb))'.
  Property 'props' does not exist on type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | (IndexRouteProps & BreadCrumb))'.
