### ISSUE TITLE
CSS HELP

### ISSUE THREAD

**Issue by RasulSonmez** [icd2k3/use-react-router-breadcrumbs#47]
Hi!
I can't modify breadcrumbs individually with css. Two separate spans come as a whole, but I can style them as a whole.
this is my code;

"
 const BreadcumbArea = () => {
  const breadcrumbs = useBreadcrumbs(routeConfig);
  return (
    <div className="breadcumbArea">

      <div className="breadcumbArea__content">
        <div className="breadcumbArea__title container">
          <div className="breadcumbArea__link">
            <>
              {breadcrumbs.map(({ match, breadcrumb }, index) => (
                <span key={match.pathname}>
                  <Link to={match.pathname}>{breadcrumb}</Link>
                  {index < breadcrumbs.length - 1 && "/"}
                </span>
              ))}
            </>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BreadcumbArea;
"

and routeconfig

"
const routesConfig = [
  { path: "/about", breadcrumb: "About Us" },

];

export default routesConfig;

"

![image](https://user-images.githubusercontent.com/58372444/160296464-a87a7bea-1546-477b-b4b5-e6aa442e12d3.png)

I want to style home separately I want to style about us separately.

thanks in advance

**Comment by icd2k3** [comment]
Hi @RasulSonmez - there's a bunch of ways you can do this, if I'm understanding correctly, you want to add a CSS class to the Link component? Something like this should do.

```js
const routesConfig = [
  { path: "/about", breadcrumb: "About Us", props: { className: 'about-us' } },
];

{breadcrumbs.map(({ match, breadcrumb, className }, index) => (
  <span key={match.pathname}>
    <Link to={match.pathname} className={className || null}>{breadcrumb}</Link>
    {index < breadcrumbs.length - 1 && "/"}
  </span>
))}
```

**Comment by RasulSonmez** [comment]
This is exactly what I wanted, thank you very much. Maybe it was an easy task as I am new to reactjs, but it was difficult for me. Thank you very much for your help.
