### ISSUE TITLE
Showing this error

### ISSUE THREAD

**Issue by ShivashankarL** [icd2k3/use-react-router-breadcrumbs#48]
Line 48:23:  React Hook "useBreadcrumbs" is called in function "index" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use"

**Comment by MichaelDimmitt** [comment]
just change the function name to Index

**Comment by icd2k3** [comment]
Thanks @MichaelDimmitt!
