### ISSUE TITLE
useLocation may only be used in context

### ISSUE THREAD

**Issue by StuartMorris0** [icd2k3/use-react-router-breadcrumbs#52]
Hey there!

I'm noticing an error for useLocation in our tests, after the latest react-router upgrade.

```  
 useLocation() may be used only in the context of a <Router> component.

      at invariant (../packages/react-router/lib/router.ts:5:20)
      at Object.useLocation (../packages/react-router/lib/hooks.tsx:75:3)
      at useReactRouterBreadcrumbs (node_modules/use-react-router-breadcrumbs/dist/cjs/index.js:278:27)
      at Breadcrumbs (src/components/Breadcrumbs/Breadcrumbs.tsx:39:26)
```

The test in question is already wrapped in a MemoryRouter etc and was working before the recent upgrade to:
``` "react-router": "^6.3.0",```

The error itself appears to come from `use-react-router-breadcrumbs`. We have a call in our Breadcrumbs component to `useLocation` imported from `react-router-dom` before which appears to be working (when lining up the error line numbers etc.), but the call from `useBreadcrumbs` does not.

Should the useLocation import be made from `react-router-dom` instead of `react-router`?

**Comment by StuartMorris0** [comment]
Just to confirm, patching the package to useLocation from `react-router-dom` does appear to resolve the error. Although interested to know if that'd be the correct approach

**Comment by icd2k3** [comment]
Hm, yea the official docs seem to be importing it from `react-router-dom` instead: https://reactrouter.com/docs/en/v6/api#uselocation

**Comment by StuartMorris0** [comment]
Created a branch if you wanted to take a look

**Comment by alex-kowalczyk** [comment]
@icd2k3 @StuartMorris0 I believe this fix is not incorporated into master branch nor any released version, effectively preventing from using this component with `react-router-dom` . 
Any chance for releasing the fix soon?

**Comment by icd2k3** [comment]
@alex-kowalczyk the main reason we use `react-router` is because it is compatible with both web DOM and `react-native` applications. `react-router-dom` is _not_ compatible with `react-native`. I am considering switching to `react-router-dom` but it might be a bit (going on vacation). I will also have to bump a major version of this package if/when that change is made since it wouldn't be compatible with `react-native` anymore.

**Comment by StuartMorris0** [comment]
I believe we got our project working without requiring a change or patch. I believe our wrappers were using the wrong react-router/react-router-dom and once playing around I found the correction configuration. 
Meaning this project required no update

**Comment by mitsol** [comment]
> 

Thanks a lot! Can you provide more infos what to do to get this work with the correct config? I'm now using v3.2.1, will this be included in the next release?

**Comment by StuartMorris0** [comment]
Unfortunately it will be specific to our project. 

As above, the error only surfaced in tests, so was related to our wrapper components and how we were using the react-router itself in the wrappers.
There was nothing related to this package and this package did not require any change to get this working.

Good luck

**Comment by mitsol** [comment]
All right! I also figured out that a downgrade to v2.0.2 works fine too without any changes. This is quick solution for me now.
