### ISSUE TITLE
Question: why react-router is peer dependency instead of react-router-dom?

### ISSUE THREAD

**Issue by sitek94** [icd2k3/use-react-router-breadcrumbs#59]
Hey there! 👋 

I'm wondering why `react-router` is set as peer dependency and not `react-router-dom`, which is [officially recommended](https://reactrouter.com/docs/en/v6/getting-started/installation#basic-installation)?

I'm asking only out of curiosity, because I got this warning:

![Screen Shot 2022-07-10 at 20 09 58](https://user-images.githubusercontent.com/58401630/178156896-23d1fdd0-2638-4d94-8830-868056bd5f23.png)

**Comment by icd2k3** [comment]
It's mostly because `react-router` is compatible with both web DOM and react native... I'm considering switching to `react-router-dom` and perhaps splitting out a different version of this util for native (if there's any demand) 🤔

**Comment by icd2k3** [comment]
v4.0.0

**Comment by sitek94** [comment]
Thanks both for explaining and migrating to `react-router-dom`, cheers! 🙇
