### ISSUE TITLE
Navigation Feature Suggestion

### ISSUE THREAD

**Issue by LouisMuriuki** [icd2k3/use-react-router-breadcrumbs#65]
Nice library you have here however, I would suggest to implement a feature whereby navigation takes place on breadcrumb click. I didnt see that in the documentation but it would be great to have.

**Comment by icd2k3** [comment]
Hi @LouisMuriuki - I wanted to keep the library un-opinionated about what link components to use, but if you check the [Advanced Example](https://github.com/icd2k3/use-react-router-breadcrumbs#advanced) it shows how to wrap the breadcrumbs in a `NavLink` component from `react-router`.

Using a `NavLink` is probably the most popular option, but by keeping it flexible users can pick whatever link component they want

**Comment by LouisMuriuki** [comment]
Okay I hadn't seen that, implemented that in my project and it works just fine👍
