### ISSUE TITLE
Giving search params/props to generated breadcrumbs on the fly?

### ISSUE THREAD

**Issue by fdrobidoux** [icd2k3/use-react-router-breadcrumbs#70]
I'm working on an app, and I have a use-case where I need to execute some stuff when I come back to a previous link in the breadcrumbs.

However, I can't figure out a way to pass some extra data in the `to` part, say, some search params, so I could potentially add `?reset=true` to specific breadcrumb links. This is because I am adding Routes defined in the element of a route in order to have recursive routes, until I reach a leaf item in a hierarchy.

Is there any way to do that? If that didn't make sense, please tell me, I'll give a better example if needed be.

**Comment by icd2k3** [comment]
hmm, you can pass extra props to breadcrumb components by including a `props: { stuff }` object in the config. Knowing when a user has gone _back_ to a previous route is an interesting use-case, though 🤔

**Comment by fdrobidoux** [comment]
It's because my breadcrumbs need to be paths that are generated on-the-fly, based on the results from a REST API which gives me folders containing other folders etc.

I might find another way to design my app so that I don't need to create dynamic routes, however.

**Comment by icd2k3** [comment]
I assume you have this working with react router? If so, you might want to check this as an alternative: https://reactrouter.com/en/main/hooks/use-matches#breadcrumbs

As of 6.4 there is an officially supported way of doing breadcrumbs in react-router - maybe it would be a little more flexible for your use case here?

**Comment by fdrobidoux** [comment]
Thanks, if I ever do React again I'll be sure to use that.
