### ISSUE TITLE
TS Error after upgrading to the latest react-router

### ISSUE THREAD

**Issue by tb-b** [icd2k3/use-react-router-breadcrumbs#71]
I've started getting this error after upgrading types and react-router to their latest version:

`node_modules/use-react-router-breadcrumbs/dist/index.d.ts:27:77 - error TS2312: An interface can only extend an object type or intersection of object types with statically known members.`

**Comment by icd2k3** [comment]
Thanks @tb-b  this should be fixed in `4.0.1`
